### ISSUE TITLE
Resolve auth issues with irods python library

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/rodeos-ingest#3]
```
Last login: Fri Dec  4 10:58:54 CET 2020
Traceback (most recent call last):
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/session.py", line 127, in server_version
    conn = next(iter(self.pool.active))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/pool.py", line 43, in get_connection
    conn = self.idle.pop()
KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods_capability_automated_ingest/irods_sync.py", line 144, in <module>
    main()
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods_capability_automated_ingest/irods_sync.py", line 140, in main
    sys.exit(args.func(args))
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods_capability_automated_ingest/irods_sync.py", line 76, in handle_start
    return start_synchronization(data)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods_capability_automated_ingest/sync_task.py", line 564, in start_synchronization
    sync_irods.validate_target_collection(data_copy, logger)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods_capability_automated_ingest/sync_irods.py", line 23, in validate_target_collection
    if not session.collections.exists('/'):
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/manager/collection_manager.py", line 76, in exists
    self.get(path)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/manager/collection_manager.py", line 15, in get
    query = self.sess.query(Collection).filter(Collection.name == path)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/session.py", line 106, in query
    return Query(self, *args)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/query.py", line 44, in __init__
    if self.sess.server_version >= col.min_version:
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/session.py", line 130, in server_version
    conn = self.pool.get_connection()
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/pool.py", line 55, in get_connection
    conn = Connection(self, self.account)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/connection.py", line 47, in __init__
    self._server_version = self._connect()
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/connection.py", line 259, in _connect
    self.ssl_startup()
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/connection.py", line 163, in ssl_startup
    wrapped_socket = context.wrap_socket(self.socket, server_hostname=host)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)
Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
Exception ignored in: <bound method Connection.__del__ of <irods.connection.Connection object at 0x7f088aadf0b8>>
Traceback (most recent call last):
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/connection.py", line 73, in __del__
    self.disconnect()
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/connection.py", line 265, in disconnect
    self.send(disconnect_msg)
  File "/opt/omics-ingest-env/lib/python3.6/site-packages/irods/connection.py", line 88, in send
    raise NetworkException("Unable to send message")
irods.exception.NetworkException: Unable to send message
```

**Comment by holtgrewe** [comment]
Hotfix by changing `irods/connection.py`

```
155         # Get or create SSL context
156         #try:
157         #    context = self.account.ssl_context
158         #except AttributeError:
159         CA_file = getattr(self.account, 'ssl_ca_certificate_file', None)
160         context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH, cafile=CA_file)

```

**Comment by holtgrewe** [comment]
https://github.com/irods/python-irodsclient/issues/237
